global.Promise = require('bluebird')
global.nanoid = require('nanoid')
global.path = require('path')
global.log4js = require('log4js')
global.fse = require('fs-extra')
global.moment = require('moment')
global.util = require('util')
global.crypto = require('crypto')
global.mongoose = require('mongoose')
global.redis = require('redis')
global.amqp = require('amqp')
global.jwt = require('jsonwebtoken')

global.Koa = require('koa')
global.logger = require('koa-logger')
global.bodyParser = require('koa-bodyparser')
global.asyncBusboy = require('async-busboy')
global.Router = require('koa-router')
